name: Go

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -o ./releases_latest/scheduller_linux_amd64 ./*.go

    - name: Build (c-shared)
      run: go build -buildmode=c-shared -o ./releases_latest/_scheduller_linux_amd64.so ./*.go
