name: scheduller_darwin_amd64

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Setup Go environment
        uses: actions/setup-go@v3.1.0
      
      - name: Build Go Module
        run: |
          go build -o ./releases_latest/scheduller_darwin_amd64 ./*.go
          go build -buildmode=c-shared -o ./releases_latest/_scheduller_darwin_amd64.so ./*.go
          python ./releases_latest/config.py
      
      - name: Push changes
        # You may pin to the exact commit or the version.
        # uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
        uses: actions-go/push@v1
        with:
          # Override the existing remote branch if it already exist
          force: false # optional
          # The name that will appear in commits when changes needs to be committed
          author-name: Github Actions # optional, default is ActionsGo Bot
          # A coma separated list of files to add to commit in addition to already staged ones. If not provided, all tracked files are committed.
          # commit-files: ./releases_latest/scheduller_linux_amd64, ./releases_latest/_scheduller_linux_amd64.so # optional
          # The commit message used when changes needs to be committed
          commit-message: Build darwin_amd64
          
          
